services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Kematjaya\RatingBundle\Calculator\RatingCalculatorInterface:
        class: Kematjaya\RatingBundle\Calculator\RatingCalculator
        
    Kematjaya\RatingBundle\Helper\AbstractRatingHelper:
        class: Kematjaya\RatingBundle\Helper\RatingHelper
        
    Kematjaya\RatingBundle\Type\RatingType: ~

    Kematjaya\RatingBundle\Twig\RatingExtension:
        tags: ['twig.extension']