services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Kematjaya\RatingBundle\Twig\RatingExtension:
        tags: ['twig.extension']
        
    Kematjaya\RatingBundle\Calculator\RatingCalculator:
        class: Kematjaya\RatingBundle\Calculator\RatingCalculator
